### ISSUE TITLE
Could it support html tags?

### ISSUE THREAD

**Issue by archonwang** [dseifert/redmine_wiki_notes#7]
@dseifert ,
Could it support html tags?
thanks.

I used redmine_ckeditor and this plugin, and I found it could not support the html tags.
could you give me some advice?

**Comment by dseifert** [comment]
I guess you need to replace the calls to textilizable in wiki_notes_macros.rb to something else. But I am not familiar with ckeditor, and actually am currently not using Redmine anymore, so I won't be able to help here. Sorry.
