### ISSUE TITLE
redcloth3, rake aborted

### ISSUE THREAD

**Issue by cowrycoin** [dseifert/redmine_wiki_notes#8]
Unfortunately I can't install your plugin. 
While I try to 

`RAILS_ENV=production bundle exec rake redmine:plugins:migrate`

rake aborted because it can't find redcloth3.

I try to install your plugin on redmine 3.4. 
`
[xxx@yyy.de]$ find . -name "redcloth3*"
./lib/redmine/wiki_formatting/textile/redcloth3.rb
`
looks like the gem redcloth3 is installed.

**Comment by dseifert** [comment]
I'm sorry, I haven't been running Redmine for a while now and this plugin is not maintained anymore by me. Try one of the newer forks, maybe this will work better for you.
