### ISSUE TITLE
Problem with Redmine 3.4.4.

### ISSUE THREAD

**Issue by younoobtoo** [dseifert/redmine_wiki_notes#9]
Hello there,

I would like to use the redmine_wiki_notes plugin on Redmine 3.4.4. Sadly I run in the folowing error as soon as I clone the repo and execute "rake redmine:plugins:migrate RAILS_ENV=production"

Because I'm a satisfied user of this plugin and I integrated it in my wiki for several times, I would be thankful if this plugin could be adapted for the new Redmine version :)

Error message:
rake aborted!
LoadError: cannot load such file -- redcloth3
/usr/local/bundle/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
/usr/local/bundle/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `block in require'
/usr/local/bundle/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/bundle/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
/usr/src/redmine/plugins/redmine_wiki_notes/init.rb:41:in `<top (required)>'
/usr/local/bundle/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
/usr/local/bundle/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `block in require'
/usr/local/bundle/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/bundle/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
/usr/src/redmine/lib/redmine/plugin.rb:155:in `block in load'
/usr/src/redmine/lib/redmine/plugin.rb:146:in `each'
/usr/src/redmine/lib/redmine/plugin.rb:146:in `load'
/usr/src/redmine/config/initializers/30-redmine.rb:21:in `<top (required)>'
/usr/local/bundle/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:268:in `load'
/usr/local/bundle/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:268:in `block in load'
/usr/local/bundle/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/bundle/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:268:in `load'
/usr/local/bundle/gems/railties-4.2.8/lib/rails/engine.rb:652:in `block in load_config_initializer'
/usr/local/bundle/gems/activesupport-4.2.8/lib/active_support/notifications.rb:166:in `instrument'
/usr/local/bundle/gems/railties-4.2.8/lib/rails/engine.rb:651:in `load_config_initializer'
/usr/local/bundle/gems/railties-4.2.8/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
/usr/local/bundle/gems/railties-4.2.8/lib/rails/engine.rb:615:in `each'
/usr/local/bundle/gems/railties-4.2.8/lib/rails/engine.rb:615:in `block in <class:Engine>'
/usr/local/bundle/gems/railties-4.2.8/lib/rails/initializable.rb:30:in `instance_exec'
/usr/local/bundle/gems/railties-4.2.8/lib/rails/initializable.rb:30:in `run'
/usr/local/bundle/gems/railties-4.2.8/lib/rails/initializable.rb:55:in `block in run_initializers'
/usr/local/bundle/gems/railties-4.2.8/lib/rails/initializable.rb:44:in `each'
/usr/local/bundle/gems/railties-4.2.8/lib/rails/initializable.rb:44:in `tsort_each_child'
/usr/local/bundle/gems/railties-4.2.8/lib/rails/initializable.rb:54:in `run_initializers'
/usr/local/bundle/gems/railties-4.2.8/lib/rails/application.rb:352:in `initialize!'
/usr/src/redmine/config/environment.rb:14:in `<top (required)>'
/usr/local/bundle/gems/railties-4.2.8/lib/rails/application.rb:328:in `require'
/usr/local/bundle/gems/railties-4.2.8/lib/rails/application.rb:328:in `require_environment!'
/usr/local/bundle/gems/railties-4.2.8/lib/rails/application.rb:457:in `block in run_tasks_blocks'
/usr/local/bundle/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)

Thanks in advance and greets, Younoobtoo

**Comment by dseifert** [comment]
As I have not been using Redmine for a couple of years now and have no further installations or RoR applications, I am afraid I won't be able to help you here. I suggest to check some of the forks, maybe somebody already updated it.
